dist: xenial  # required for Python >= 3.7
language: python
python:
  - '3.6'
  - '3.7'
cache: pip
install:
  - pip install -r test-requirements.txt
script:
  - make tests docs
deploy:
  provider: pypi
  user: tillahoffmann
  skip_existing: true
  password:
    secure: FslZOY1bC3dUM4GhrVbrpf2yPZNj1W/M2qSuV1xUVAOJPQ4QprXCOh6F/CGh3kAuKyaImc+xp45qpPIUxbkLoUvXmr6vSD/w+NLqmsuS2fG3HTneh82Uioqm6z3WIqrln8mc8rffzv6+ZBZ34X62k7Tw3qaViuzI5JKBgGvkPwUCFcF7Z7ku00xMX2r+Y/S+1pN2lxOGtbb8jqpGjWN17D6D+UNBUAkoBNYFJpt7v4LCDrDUH0wP5DQ7xmLDuirR7Zw9+b38TcugceEh55D6rwYdgZlwAY43mevytRxQQHjl+qlA6CQKZCSsSD5baMF9ixhcLwKPjAHdS9TqWOI2OCyb40SSZ0W85oOYbaHcyOCQBmiqm77amU+QewRb+dDjbCM0f+F4a7+1wE/8cKMZIWyP01J8lDS0So0/ZhZNLNrHHRRQK61nlvSZLsPYlk1IOEa6zaMfPKuEG4SD/8hLWNZvEn44oB0o3RFW2iCTpvvoHJiReOjoFy3hV+AfbPPxI8AiZgJ9fVQai5YE0Gn7sXNpep/UF8WM8OgN0+/6J3KWe+qRce+h5i64zhJWxo/TzHKexreWC3mObYnvUayb4uXot5pt4lmBdK4/qqpAXrlXBRQksCg7F2to7qM641urqbhhdOc4sTo6MTMpMvMDyaqGIuaYDsQh2VMw0prWWVo=
